### ISSUE TITLE
why i got the 502

### ISSUE THREAD

**Issue by joykaiyo** [alfg/docker-nginx-vod-module#4] opened 2018-04-29 03:59 UTC
now i want it ensure i can got the hls from aws mp4
should i do anyelse to change my bucket setting?

**Comment by alfg** [comment] 2018-05-01 21:28
Hi @cjk7713, 

Are you creating the aws signing key used by:
https://github.com/alfg/docker-nginx-vod-module/blob/master/nginx.remote.conf#L52

https://github.com/alfg/docker-nginx-vod-module/blob/master/scripts/generate_signing_key.py

**Comment by mlevkov** [comment] 2018-05-02 01:41
Same here, I've gotten 502 Bad Gateway error. I did create they key. The error log does say that I've gotten 403 Forbidden error. However, I've checked the configuration and it looks correct (at least it seems to be so). My credentials do allow use of CLI (which according to the AWS is specified as programmatic access). If you are open to it, I can make a web session to show you what the issue is, if that helps.

**Comment by alfg** [comment] 2018-05-02 04:06
Ok, so I tried doing a fresh docker build, with a new signing key and key scope. I'm still able to resolve a video:
```
λ curl -I http://localhost:8080/hls/videos/tears-of-steel/video.mp4/master.m3u8
HTTP/1.1 200 OK
Server: nginx/1.13.8
Date: Wed, 02 May 2018 04:01:42 GMT
Content-Type: application/vnd.apple.mpegurl
Content-Length: 238
Connection: keep-alive
ETag: "-1-ee"
Access-Control-Allow-Headers: *
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Accept-Ranges: bytes
```

My test video is stored in the s3 bucket, under `videos/tears-of-steel/video.mp4` in the case above. I got a 502 when entering an incorrect path.

Can you double check you are entering the correct path for your video? If you're still running into issues, can you provide a minimal example or demo? I wonder if can also be an AWS permissions thing.

**Comment by alfg** [comment] 2018-05-14 01:30
Closing this for now. Feel free to reopen if you're still running into issues.

**Closed as completed by alfg** 2018-05-14 01:30 UTC

**Comment by RomanGalo4kin** [comment] 2020-08-15 08:24
I got the same error with default settings.

**Comment by alfg** [comment] 2020-08-15 09:08
It's usually due to an invalid signing key. Make sure to run:
```
python scripts/generate_signing_key.py -k <aws secret access key> -r <aws region>
```

and apply those values as the environment variables:
```
AWS_SIGNING_KEY=
AWS_KEY_SCOPE=
```
